name = "main"
uuid = "70fbf7c6-2f8c-431c-b73b-6bd747db0edf"
authors = ["Hamish Hay <hamish@tides.rocks>", "Marijn van Dijk <m.r.van.dijk.3@student.rug.nl>", "Tim Lichtenberg <tim.lichtenberg@rug.nl>", "Harrison Nicholls <harrison.nicholls@physics.ox.ac.uk>"]
version = "0.1.0"

[deps]
AssociatedLegendrePolynomials = "2119f1ac-fb78-50f5-8cc0-dda848ebdb19"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
FFTW = "1.10.0"
Interpolations = "0.16.2"
JSON = "1.3.0"
LoggingExtras = "1.2.0"
Plots = "1.41.2"
Printf = "1.11.0"
TOML = "1.0.3"
